# Generated by Django 3.0.5 on 2020-05-05 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_ownership', models.CharField(choices=[('ООО', 'ООО'), ('ПАО', 'ПАО'), ('АО', 'АО')], default='ООО', max_length=100, verbose_name='Форма собственности')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='deals.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.Contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Сделку',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('probability_of_success', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вероятность успеха сделки')),
            ],
            options={
                'verbose_name': 'Стадию сделки',
                'verbose_name_plural': 'Стадии сделок',
            },
        ),
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], db_index=True, default='RUB', max_length=100, verbose_name='Валюта')),
                ('expected_deal_date', models.DateField(db_index=True, verbose_name='Дата предполагаемого совершения сделки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания текущей записи')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='deals.Deal', verbose_name='Сделка')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='deals.DealStage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Состояние сделки',
                'verbose_name_plural': 'Состояния сделок',
            },
        ),
    ]
